language: ruby

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: thuy.life
  acl: public_read
  on:
    repo: ThuyNT13/thuy_life

install: true

script: true
